# Generated by Django 4.2.3 on 2023-07-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nasc',
            field=models.DateTimeField(null=True),
        ),
    ]
