# Generated by Django 4.2.3 on 2023-07-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste1', '0002_usuario_cpf_usuario_data_nasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nasc',
            field=models.DateField(null=True),
        ),
    ]
